name: sourdough-go-web-k8s-infra
description: The infrastructure setup of this go program
runtime:
  name: go
  options:
    binary: bin/sourdough-go-web-k8s-infra
config:
  pulumi:tags:
    value:
      pulumi:template: go
