name: Deploy to Production Kubernetes

on:
  workflow_dispatch:

env:
  CONTAINER_TAG: gitea-${{ gitea.sha }}
jobs:
  build_and_push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - uses: actions/setup-go@v5
        name: Set up Go
        with:
         go-version: '1.22'
      - name: Install musl-tools
        run: sudo apt-get update && sudo apt-get install -y musl-tools
      - name: Pulumi Deploy
        env:
          BWS_ACCESS_TOKEN: ${{ secrets.BWS_ACCESS_TOKEN }}
        run: |
          ./build.sh --pulumi-deploy --docker-tag ${{ env.CONTAINER_TAG }} --env production
